/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import { User, EventDetails, Participant, ScanLog, UserRole, PassStatus, EmailLog } from '../types.js';

// Simple in-memory storage backed by a JSON file
let DB_FILE = path.join(process.cwd(), 'db.json');

// Optimize for serverless environments (like Vercel) where the root filesystem is read-only
if (process.env.VERCEL || process.env.NODE_ENV === 'production') {
  const tempDbPath = path.join('/tmp', 'db.json');
  try {
    if (!fs.existsSync(tempDbPath)) {
      if (fs.existsSync(DB_FILE)) {
        fs.copyFileSync(DB_FILE, tempDbPath);
      }
    }
    DB_FILE = tempDbPath;
  } catch (err) {
    console.error('Failed to copy db.json to /tmp, falling back to local path:', err);
  }
}

interface DatabaseSchema {
  users: User[];
  events: EventDetails[];
  participants: Participant[];
  scanLogs: ScanLog[];
  emailLogs?: EmailLog[];
}

function hashPassword(password: string): string {
  return crypto.createHash('sha256').update(password).digest('hex');
}

const DEFAULT_EVENT_ID = 'event-1';

const defaultDb: DatabaseSchema = {
  users: [
    {
      id: 'user-admin',
      name: 'ETSNTECH Admin',
      email: 'admin@etsntech.org',
      role: UserRole.ADMIN,
      passwordHash: hashPassword('admin123'),
      createdAt: new Date().toISOString(),
    },
    {
      id: 'user-gate',
      name: 'Gate Officer 1',
      email: 'gate@etsntech.org',
      role: UserRole.GATE_OFFICER,
      passwordHash: hashPassword('gate123'),
      createdAt: new Date().toISOString(),
    }
  ],
  events: [
    {
      id: DEFAULT_EVENT_ID,
      eventName: 'ETS N-TECH Tech Summit 2026',
      eventDate: '2026-07-25',
      eventTime: '09:00',
      venue: 'ETSNTECH Innovation Hub, Abuja, Nigeria',
      organizerName: 'ETS N-TECH',
      description: 'Annual technology exhibition and summits highlighting societal problem-solving IT systems.',
      passTitle: 'DELEGATE PASS',
      accessInstruction: 'This pass is valid for one entry only. Please present it at the entrance for verification.',
      footerNote: 'Generated by ETSNTECH Event Access System.',
      logoPath: '',
      primaryColor: '#0f172a', // Slate 900
      accentColor: '#eab308', // Gold / Warm Yellow
      showPhone: true,
      showEmail: true,
      showCategory: true,
      showOrganization: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }
  ],
  participants: [
    {
      id: 'part-1',
      eventId: DEFAULT_EVENT_ID,
      fullName: 'John Doe',
      phone: '+234 812 345 6789',
      email: 'johndoe@example.com',
      organization: 'Tech Innovations Ltd',
      category: 'VIP',
      passId: 'ETSN-2026-0001-X7K9',
      status: PassStatus.NOT_USED,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'part-2',
      eventId: DEFAULT_EVENT_ID,
      fullName: 'Mary Claire',
      phone: '+234 803 111 2222',
      email: 'maryclaire@example.com',
      organization: 'Greenfield Corp',
      category: 'Exhibitor',
      passId: 'ETSN-2026-0002-K8M4',
      status: PassStatus.USED,
      checkedInAt: '2026-07-08T10:30:00Z',
      checkedInBy: 'Gate Officer 1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'part-3',
      eventId: DEFAULT_EVENT_ID,
      fullName: 'Patrick Mboa',
      phone: '+234 805 444 5555',
      email: 'mboa@example.com',
      organization: 'University of Abuja',
      category: 'Student',
      passId: 'ETSN-2026-0003-P2Q6',
      status: PassStatus.NOT_USED,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }
  ],
  scanLogs: [],
  emailLogs: []
};

class DB {
  private data: DatabaseSchema = defaultDb;
  private supabase: SupabaseClient | null = null;
  public useSupabase = false;

  constructor() {
    this.initSupabase();
    if (!this.useSupabase) {
      this.loadLocal();
    }
  }

  private initSupabase() {
    const url = process.env.SUPABASE_URL || '';
    const key = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_ANON_KEY || '';
    if (url && key) {
      try {
        this.supabase = createClient(url, key, {
          auth: {
            persistSession: false
          }
        });
        this.useSupabase = true;
        console.log('[DB] Supabase connection initialized successfully!');
        
        // Seed database in the background
        this.seedSupabase().catch(err => {
          console.error('[DB] Error seeding Supabase:', err);
        });
      } catch (err) {
        console.error('[DB] Failed to initialize Supabase client:', err);
        this.useSupabase = false;
      }
    } else {
      console.log('[DB] Supabase credentials not found in environment. Using local JSON database.');
    }
  }

  private async seedSupabase() {
    if (!this.supabase) return;
    try {
      console.log('[DB] Checking table schemas and seeding defaults in Supabase...');

      // 1. Check & Seed Event
      const { data: eventData, error: eventErr } = await this.supabase
        .from('events')
        .select('id')
        .limit(1);

      if (eventErr) {
        console.warn('[DB] Could not query "events" table (it might not exist yet). Error:', eventErr.message);
        return;
      }

      if (!eventData || eventData.length === 0) {
        console.log('[DB] Seeding default event to Supabase events table...');
        const { error: insErr } = await this.supabase
          .from('events')
          .insert(defaultDb.events);
        if (insErr) console.error('[DB] Failed to seed default event:', insErr.message);
      }

      // 2. Check & Seed Users
      const { data: userData, error: userErr } = await this.supabase
        .from('users')
        .select('id')
        .limit(1);

      if (!userErr && (!userData || userData.length === 0)) {
        console.log('[DB] Seeding default users to Supabase users table...');
        const { error: insErr } = await this.supabase
          .from('users')
          .insert(defaultDb.users);
        if (insErr) console.error('[DB] Failed to seed default users:', insErr.message);
      }

      // 3. Check & Seed Participants
      const { data: partData, error: partErr } = await this.supabase
        .from('participants')
        .select('id')
        .limit(1);

      if (!partErr && (!partData || partData.length === 0)) {
        console.log('[DB] Seeding default participants to Supabase participants table...');
        const { error: insErr } = await this.supabase
          .from('participants')
          .insert(defaultDb.participants);
        if (insErr) console.error('[DB] Failed to seed default participants:', insErr.message);
      }
    } catch (err) {
      console.error('[DB] Unexpected error seeding Supabase:', err);
    }
  }

  private loadLocal() {
    try {
      if (fs.existsSync(DB_FILE)) {
        const content = fs.readFileSync(DB_FILE, 'utf-8');
        this.data = JSON.parse(content);
        // Ensure defaults if any properties are missing
        if (!this.data.users) this.data.users = defaultDb.users;
        if (!this.data.events) this.data.events = defaultDb.events;
        if (!this.data.participants) this.data.participants = defaultDb.participants;
        if (!this.data.scanLogs) this.data.scanLogs = defaultDb.scanLogs;
        if (!this.data.emailLogs) this.data.emailLogs = [];
      } else {
        this.saveLocal();
      }
    } catch (error) {
      console.error('Error loading database, using in-memory defaults:', error);
      this.data = defaultDb;
    }
  }

  private saveLocal() {
    try {
      fs.writeFileSync(DB_FILE, JSON.stringify(this.data, null, 2), 'utf-8');
    } catch (error) {
      console.error('Error saving database:', error);
    }
  }

  // --- Users Methods ---
  async getUsers(): Promise<User[]> {
    if (this.useSupabase && this.supabase) {
      const { data, error } = await this.supabase.from('users').select('*');
      if (!error && data) return data as User[];
      console.error('[DB] Supabase getUsers error, falling back to local:', error?.message);
    }
    return this.data.users;
  }

  async getUserByEmail(email: string): Promise<User | undefined> {
    if (this.useSupabase && this.supabase) {
      const { data, error } = await this.supabase
        .from('users')
        .select('*')
        .eq('email', email.trim())
        .maybeSingle();
      if (!error && data) return data as User;
      if (error) console.error('[DB] Supabase getUserByEmail error:', error.message);
    }
    return this.data.users.find(u => u.email.toLowerCase() === email.toLowerCase());
  }

  async verifyUser(email: string, passwordPlain: string): Promise<User | undefined> {
    const user = await this.getUserByEmail(email);
    if (!user) return undefined;
    const hash = hashPassword(passwordPlain);
    if (user.passwordHash === hash) {
      return user;
    }
    return undefined;
  }

  async createUser(user: Omit<User, 'id' | 'passwordHash' | 'createdAt'>, passwordPlain: string): Promise<User> {
    const newUser: User = {
      ...user,
      id: 'user-' + Math.random().toString(36).substring(2, 9),
      passwordHash: hashPassword(passwordPlain),
      createdAt: new Date().toISOString()
    };

    if (this.useSupabase && this.supabase) {
      const { error } = await this.supabase.from('users').insert(newUser);
      if (!error) return newUser;
      console.error('[DB] Supabase createUser error, falling back to local:', error.message);
    }

    this.data.users.push(newUser);
    this.saveLocal();
    return newUser;
  }

  // --- Events Methods ---
  async getEvents(): Promise<EventDetails[]> {
    if (this.useSupabase && this.supabase) {
      const { data, error } = await this.supabase.from('events').select('*');
      if (!error && data) return data as EventDetails[];
      console.error('[DB] Supabase getEvents error, falling back to local:', error?.message);
    }
    return this.data.events;
  }

  async getEvent(id: string = DEFAULT_EVENT_ID): Promise<EventDetails | undefined> {
    if (this.useSupabase && this.supabase) {
      const { data, error } = await this.supabase
        .from('events')
        .select('*')
        .eq('id', id)
        .maybeSingle();
      if (!error && data) return data as EventDetails;

      const { data: firstEvent } = await this.supabase.from('events').select('*').limit(1);
      if (firstEvent && firstEvent.length > 0) return firstEvent[0] as EventDetails;

      if (error) console.error('[DB] Supabase getEvent error:', error.message);
    }
    return this.data.events.find(e => e.id === id) || this.data.events[0];
  }

  async updateEvent(id: string, updates: Partial<Omit<EventDetails, 'id' | 'createdAt'>>): Promise<EventDetails> {
    const updatedAt = new Date().toISOString();

    if (this.useSupabase && this.supabase) {
      const { data, error } = await this.supabase
        .from('events')
        .update({ ...updates, updatedAt })
        .eq('id', id)
        .select()
        .maybeSingle();

      if (!error && data) {
        return data as EventDetails;
      }

      const newEvent: EventDetails = {
        id,
        eventName: updates.eventName || 'ETS N-TECH Event',
        eventDate: updates.eventDate || '',
        eventTime: updates.eventTime || '',
        venue: updates.venue || '',
        organizerName: updates.organizerName || 'ETS N-TECH',
        description: updates.description || '',
        passTitle: updates.passTitle || 'EVENT PASS',
        accessInstruction: updates.accessInstruction || '',
        footerNote: updates.footerNote || '',
        logoPath: updates.logoPath || '',
        primaryColor: updates.primaryColor || '#0f172a',
        accentColor: updates.accentColor || '#eab308',
        showPhone: updates.showPhone !== undefined ? updates.showPhone : true,
        showEmail: updates.showEmail !== undefined ? updates.showEmail : true,
        showCategory: updates.showCategory !== undefined ? updates.showCategory : true,
        showOrganization: updates.showOrganization !== undefined ? updates.showOrganization : true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
      };

      const { error: insErr } = await this.supabase.from('events').insert(newEvent);
      if (!insErr) return newEvent;
      console.error('[DB] Supabase updateEvent error, falling back to local:', insErr.message);
    }

    const index = this.data.events.findIndex(e => e.id === id);
    if (index === -1) {
      const newEvent: EventDetails = {
        id,
        eventName: updates.eventName || 'ETS N-TECH Event',
        eventDate: updates.eventDate || '',
        eventTime: updates.eventTime || '',
        venue: updates.venue || '',
        organizerName: updates.organizerName || 'ETS N-TECH',
        description: updates.description || '',
        passTitle: updates.passTitle || 'EVENT PASS',
        accessInstruction: updates.accessInstruction || '',
        footerNote: updates.footerNote || '',
        logoPath: updates.logoPath || '',
        primaryColor: updates.primaryColor || '#0f172a',
        accentColor: updates.accentColor || '#eab308',
        showPhone: updates.showPhone !== undefined ? updates.showPhone : true,
        showEmail: updates.showEmail !== undefined ? updates.showEmail : true,
        showCategory: updates.showCategory !== undefined ? updates.showCategory : true,
        showOrganization: updates.showOrganization !== undefined ? updates.showOrganization : true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
      };
      this.data.events.push(newEvent);
      this.saveLocal();
      return newEvent;
    } else {
      this.data.events[index] = {
        ...this.data.events[index],
        ...updates,
        updatedAt
      };
      this.saveLocal();
      return this.data.events[index];
    }
  }

  // --- Participants Methods ---
  async getParticipants(): Promise<Participant[]> {
    if (this.useSupabase && this.supabase) {
      const { data, error } = await this.supabase.from('participants').select('*');
      if (!error && data) return data as Participant[];
      console.error('[DB] Supabase getParticipants error, falling back to local:', error?.message);
    }
    return this.data.participants;
  }

  async getParticipantById(id: string): Promise<Participant | undefined> {
    if (this.useSupabase && this.supabase) {
      const { data, error } = await this.supabase
        .from('participants')
        .select('*')
        .eq('id', id)
        .maybeSingle();
      if (!error && data) return data as Participant;
      if (error) console.error('[DB] Supabase getParticipantById error:', error.message);
    }
    return this.data.participants.find(p => p.id === id);
  }

  async getParticipantByPassId(passId: string): Promise<Participant | undefined> {
    const trimmed = passId.toUpperCase().trim();
    if (this.useSupabase && this.supabase) {
      const { data, error } = await this.supabase
        .from('participants')
        .select('*')
        .eq('passId', trimmed)
        .maybeSingle();
      if (!error && data) return data as Participant;
      if (error) console.error('[DB] Supabase getParticipantByPassId error:', error.message);
    }
    return this.data.participants.find(p => p.passId.toUpperCase().trim() === trimmed);
  }

  async createParticipant(participant: Omit<Participant, 'id' | 'passId' | 'createdAt' | 'updatedAt'>): Promise<Participant> {
    const randomSuffix = Math.random().toString(36).substring(2, 6).toUpperCase();

    let count = this.data.participants.length + 1;
    if (this.useSupabase && this.supabase) {
      const { count: dbCount, error } = await this.supabase
        .from('participants')
        .select('*', { count: 'exact', head: true });
      if (!error && dbCount !== null) {
        count = dbCount + 1;
      }
    }

    const formattedCount = String(count).padStart(4, '0');
    const passId = `ETSN-2026-${formattedCount}-${randomSuffix}`;

    const newPart: Participant = {
      ...participant,
      id: 'part-' + Math.random().toString(36).substring(2, 9),
      passId,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    };

    if (this.useSupabase && this.supabase) {
      const { error } = await this.supabase.from('participants').insert(newPart);
      if (!error) return newPart;
      console.error('[DB] Supabase createParticipant error, falling back to local:', error.message);
    }

    this.data.participants.push(newPart);
    this.saveLocal();
    return newPart;
  }

  async createParticipantsBatch(batch: Omit<Participant, 'id' | 'passId' | 'createdAt' | 'updatedAt'>[]): Promise<Participant[]> {
    const created: Participant[] = [];

    let currentCount = this.data.participants.length;
    if (this.useSupabase && this.supabase) {
      const { count: dbCount, error } = await this.supabase
        .from('participants')
        .select('*', { count: 'exact', head: true });
      if (!error && dbCount !== null) {
        currentCount = dbCount;
      }
    }

    for (const item of batch) {
      currentCount++;
      const randomSuffix = Math.random().toString(36).substring(2, 6).toUpperCase();
      const formattedCount = String(currentCount).padStart(4, '0');
      const passId = `ETSN-2026-${formattedCount}-${randomSuffix}`;

      const newPart: Participant = {
        ...item,
        id: 'part-' + Math.random().toString(36).substring(2, 9),
        passId,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
      };
      created.push(newPart);
    }

    if (this.useSupabase && this.supabase) {
      const { error } = await this.supabase.from('participants').insert(created);
      if (!error) return created;
      console.error('[DB] Supabase createParticipantsBatch error, falling back to local:', error.message);
    }

    this.data.participants.push(...created);
    this.saveLocal();
    return created;
  }

  async updateParticipant(id: string, updates: Partial<Omit<Participant, 'id' | 'passId' | 'createdAt'>>): Promise<Participant | undefined> {
    const updatedAt = new Date().toISOString();

    if (this.useSupabase && this.supabase) {
      const { data, error } = await this.supabase
        .from('participants')
        .update({ ...updates, updatedAt })
        .eq('id', id)
        .select()
        .maybeSingle();
      if (!error && data) return data as Participant;
      console.error('[DB] Supabase updateParticipant error, falling back to local:', error?.message);
    }

    const index = this.data.participants.findIndex(p => p.id === id);
    if (index === -1) return undefined;

    this.data.participants[index] = {
      ...this.data.participants[index],
      ...updates,
      updatedAt
    };
    this.saveLocal();
    return this.data.participants[index];
  }

  async deleteParticipant(id: string): Promise<boolean> {
    if (this.useSupabase && this.supabase) {
      const { error } = await this.supabase.from('participants').delete().eq('id', id);
      if (!error) return true;
      console.error('[DB] Supabase deleteParticipant error, falling back to local:', error.message);
    }

    const index = this.data.participants.findIndex(p => p.id === id);
    if (index === -1) return false;
    this.data.participants.splice(index, 1);
    this.saveLocal();
    return true;
  }

  async deleteParticipantsBatch(ids: string[]): Promise<boolean> {
    if (this.useSupabase && this.supabase) {
      const { error } = await this.supabase.from('participants').delete().in('id', ids);
      if (!error) return true;
      console.error('[DB] Supabase deleteParticipantsBatch error, falling back to local:', error.message);
    }

    const initialLength = this.data.participants.length;
    this.data.participants = this.data.participants.filter(p => !ids.includes(p.id));
    this.saveLocal();
    return this.data.participants.length < initialLength;
  }

  // --- Scan Logs Methods ---
  async getScanLogs(): Promise<ScanLog[]> {
    let scanLogs: ScanLog[] = [];
    if (this.useSupabase && this.supabase) {
      const { data, error } = await this.supabase.from('scanLogs').select('*');
      if (!error && data) {
        scanLogs = data as ScanLog[];
      } else {
        console.error('[DB] Supabase getScanLogs error, falling back to local:', error?.message);
        scanLogs = this.data.scanLogs;
      }
    } else {
      scanLogs = this.data.scanLogs;
    }

    const hydratedLogs = [];
    for (const log of scanLogs) {
      const part = await this.getParticipantByPassId(log.passId);
      hydratedLogs.push({
        ...log,
        participantName: part ? part.fullName : log.participantName || 'Unknown'
      });
    }
    return hydratedLogs;
  }

  async addScanLog(log: Omit<ScanLog, 'id' | 'createdAt'>): Promise<ScanLog> {
    const newLog: ScanLog = {
      ...log,
      id: 'log-' + Math.random().toString(36).substring(2, 9),
      createdAt: new Date().toISOString()
    };

    if (this.useSupabase && this.supabase) {
      const { error } = await this.supabase.from('scanLogs').insert(newLog);
      if (!error) return newLog;
      console.error('[DB] Supabase addScanLog error, falling back to local:', error.message);
    }

    this.data.scanLogs.push(newLog);
    this.saveLocal();
    return newLog;
  }

  async clearScanLogs(): Promise<void> {
    if (this.useSupabase && this.supabase) {
      const { error } = await this.supabase.from('scanLogs').delete().neq('id', '');
      if (!error) return;
      console.error('[DB] Supabase clearScanLogs error, falling back to local:', error.message);
    }

    this.data.scanLogs = [];
    this.saveLocal();
  }

  // --- Email Logs Methods ---
  async getEmailLogs(): Promise<EmailLog[]> {
    if (this.useSupabase && this.supabase) {
      const { data, error } = await this.supabase.from('emailLogs').select('*');
      if (!error && data) return data as EmailLog[];
      console.error('[DB] Supabase getEmailLogs error, falling back to local:', error?.message);
    }
    return this.data.emailLogs || [];
  }

  async addEmailLog(log: Omit<EmailLog, 'id' | 'sentAt'>): Promise<EmailLog> {
    const newLog: EmailLog = {
      ...log,
      id: 'eml-' + Math.random().toString(36).substring(2, 9),
      sentAt: new Date().toISOString()
    };

    if (this.useSupabase && this.supabase) {
      const { error } = await this.supabase.from('emailLogs').insert(newLog);
      if (!error) return newLog;
      console.error('[DB] Supabase addEmailLog error, falling back to local:', error.message);
    }

    if (!this.data.emailLogs) this.data.emailLogs = [];
    this.data.emailLogs.push(newLog);
    this.saveLocal();
    return newLog;
  }

  async updateEmailLogStatus(id: string, status: 'Queued' | 'Sending' | 'Delivered' | 'Failed', errorMessage?: string): Promise<EmailLog | undefined> {
    const sentAt = new Date().toISOString();

    if (this.useSupabase && this.supabase) {
      const { data, error } = await this.supabase
        .from('emailLogs')
        .update({ status, errorMessage, sentAt })
        .eq('id', id)
        .select()
        .maybeSingle();
      if (!error && data) return data as EmailLog;
      console.error('[DB] Supabase updateEmailLogStatus error, falling back to local:', error?.message);
    }

    if (!this.data.emailLogs) this.data.emailLogs = [];
    const index = this.data.emailLogs.findIndex(l => l.id === id);
    if (index === -1) return undefined;
    this.data.emailLogs[index] = {
      ...this.data.emailLogs[index],
      status,
      errorMessage,
      sentAt
    };
    this.saveLocal();
    return this.data.emailLogs[index];
  }

  async clearEmailLogs(): Promise<void> {
    if (this.useSupabase && this.supabase) {
      const { error } = await this.supabase.from('emailLogs').delete().neq('id', '');
      if (!error) return;
      console.error('[DB] Supabase clearEmailLogs error, falling back to local:', error.message);
    }

    this.data.emailLogs = [];
    this.saveLocal();
  }
}

export const db = new DB();
