/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import { User, EventDetails, Participant, ScanLog, UserRole, PassStatus } from '../types.js';

// Simple in-memory storage backed by a JSON file
const DB_FILE = path.join(process.cwd(), 'db.json');

interface DatabaseSchema {
  users: User[];
  events: EventDetails[];
  participants: Participant[];
  scanLogs: ScanLog[];
}

function hashPassword(password: string): string {
  return crypto.createHash('sha256').update(password).digest('hex');
}

const DEFAULT_EVENT_ID = 'event-1';

const defaultDb: DatabaseSchema = {
  users: [
    {
      id: 'user-admin',
      name: 'ETSNTECH Admin',
      email: 'admin@etsntech.org',
      role: UserRole.ADMIN,
      passwordHash: hashPassword('admin123'),
      createdAt: new Date().toISOString(),
    },
    {
      id: 'user-gate',
      name: 'Gate Officer 1',
      email: 'gate@etsntech.org',
      role: UserRole.GATE_OFFICER,
      passwordHash: hashPassword('gate123'),
      createdAt: new Date().toISOString(),
    }
  ],
  events: [
    {
      id: DEFAULT_EVENT_ID,
      eventName: 'ETS N-TECH Tech Summit 2026',
      eventDate: '2026-07-25',
      eventTime: '09:00',
      venue: 'ETSNTECH Innovation Hub, Abuja, Nigeria',
      organizerName: 'ETS N-TECH',
      description: 'Annual technology exhibition and summits highlighting societal problem-solving IT systems.',
      passTitle: 'DELEGATE PASS',
      accessInstruction: 'This pass is valid for one entry only. Please present it at the entrance for verification.',
      footerNote: 'Generated by ETSNTECH Event Access System.',
      logoPath: '',
      primaryColor: '#0f172a', // Slate 900
      accentColor: '#eab308', // Gold / Warm Yellow
      showPhone: true,
      showEmail: true,
      showCategory: true,
      showOrganization: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }
  ],
  participants: [
    {
      id: 'part-1',
      eventId: DEFAULT_EVENT_ID,
      fullName: 'John Doe',
      phone: '+234 812 345 6789',
      email: 'johndoe@example.com',
      organization: 'Tech Innovations Ltd',
      category: 'VIP',
      passId: 'ETSN-2026-0001-X7K9',
      status: PassStatus.NOT_USED,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'part-2',
      eventId: DEFAULT_EVENT_ID,
      fullName: 'Mary Claire',
      phone: '+234 803 111 2222',
      email: 'maryclaire@example.com',
      organization: 'Greenfield Corp',
      category: 'Exhibitor',
      passId: 'ETSN-2026-0002-K8M4',
      status: PassStatus.USED,
      checkedInAt: '2026-07-08T10:30:00Z',
      checkedInBy: 'Gate Officer 1',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'part-3',
      eventId: DEFAULT_EVENT_ID,
      fullName: 'Patrick Mboa',
      phone: '+234 805 444 5555',
      email: 'mboa@example.com',
      organization: 'University of Abuja',
      category: 'Student',
      passId: 'ETSN-2026-0003-P2Q6',
      status: PassStatus.NOT_USED,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }
  ],
  scanLogs: []
};

class DB {
  private data: DatabaseSchema = defaultDb;

  constructor() {
    this.load();
  }

  private load() {
    try {
      if (fs.existsSync(DB_FILE)) {
        const content = fs.readFileSync(DB_FILE, 'utf-8');
        this.data = JSON.parse(content);
        // Ensure defaults if any properties are missing
        if (!this.data.users) this.data.users = defaultDb.users;
        if (!this.data.events) this.data.events = defaultDb.events;
        if (!this.data.participants) this.data.participants = defaultDb.participants;
        if (!this.data.scanLogs) this.data.scanLogs = defaultDb.scanLogs;
      } else {
        this.save();
      }
    } catch (error) {
      console.error('Error loading database, using in-memory defaults:', error);
      this.data = defaultDb;
    }
  }

  private save() {
    try {
      fs.writeFileSync(DB_FILE, JSON.stringify(this.data, null, 2), 'utf-8');
    } catch (error) {
      console.error('Error saving database:', error);
    }
  }

  // --- Users Methods ---
  getUsers(): User[] {
    return this.data.users;
  }

  getUserByEmail(email: string): User | undefined {
    return this.data.users.find(u => u.email.toLowerCase() === email.toLowerCase());
  }

  verifyUser(email: string, passwordPlain: string): User | undefined {
    const user = this.getUserByEmail(email);
    if (!user) return undefined;
    const hash = hashPassword(passwordPlain);
    if (user.passwordHash === hash) {
      return user;
    }
    return undefined;
  }

  createUser(user: Omit<User, 'id' | 'passwordHash' | 'createdAt'>, passwordPlain: string): User {
    const newUser: User = {
      ...user,
      id: 'user-' + Math.random().toString(36).substring(2, 9),
      passwordHash: hashPassword(passwordPlain),
      createdAt: new Date().toISOString()
    };
    this.data.users.push(newUser);
    this.save();
    return newUser;
  }

  // --- Events Methods ---
  getEvents(): EventDetails[] {
    return this.data.events;
  }

  getEvent(id: string = DEFAULT_EVENT_ID): EventDetails | undefined {
    return this.data.events.find(e => e.id === id) || this.data.events[0];
  }

  updateEvent(id: string, updates: Partial<Omit<EventDetails, 'id' | 'createdAt'>>): EventDetails {
    const index = this.data.events.findIndex(e => e.id === id);
    if (index === -1) {
      // Create new
      const newEvent: EventDetails = {
        id,
        eventName: updates.eventName || 'ETS N-TECH Event',
        eventDate: updates.eventDate || '',
        eventTime: updates.eventTime || '',
        venue: updates.venue || '',
        organizerName: updates.organizerName || 'ETS N-TECH',
        description: updates.description || '',
        passTitle: updates.passTitle || 'EVENT PASS',
        accessInstruction: updates.accessInstruction || '',
        footerNote: updates.footerNote || '',
        logoPath: updates.logoPath || '',
        primaryColor: updates.primaryColor || '#0f172a',
        accentColor: updates.accentColor || '#eab308',
        showPhone: updates.showPhone !== undefined ? updates.showPhone : true,
        showEmail: updates.showEmail !== undefined ? updates.showEmail : true,
        showCategory: updates.showCategory !== undefined ? updates.showCategory : true,
        showOrganization: updates.showOrganization !== undefined ? updates.showOrganization : true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
      };
      this.data.events.push(newEvent);
      this.save();
      return newEvent;
    } else {
      this.data.events[index] = {
        ...this.data.events[index],
        ...updates,
        updatedAt: new Date().toISOString()
      };
      this.save();
      return this.data.events[index];
    }
  }

  // --- Participants Methods ---
  getParticipants(): Participant[] {
    return this.data.participants;
  }

  getParticipantById(id: string): Participant | undefined {
    return this.data.participants.find(p => p.id === id);
  }

  getParticipantByPassId(passId: string): Participant | undefined {
    return this.data.participants.find(p => p.passId.toUpperCase().trim() === passId.toUpperCase().trim());
  }

  createParticipant(participant: Omit<Participant, 'id' | 'passId' | 'createdAt' | 'updatedAt'>): Participant {
    const randomSuffix = Math.random().toString(36).substring(2, 6).toUpperCase();
    const count = this.data.participants.length + 1;
    const formattedCount = String(count).padStart(4, '0');
    const passId = `ETSN-2026-${formattedCount}-${randomSuffix}`;

    const newPart: Participant = {
      ...participant,
      id: 'part-' + Math.random().toString(36).substring(2, 9),
      passId,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    };
    this.data.participants.push(newPart);
    this.save();
    return newPart;
  }

  createParticipantsBatch(batch: Omit<Participant, 'id' | 'passId' | 'createdAt' | 'updatedAt'>[]): Participant[] {
    const created: Participant[] = [];
    let currentCount = this.data.participants.length;

    for (const item of batch) {
      currentCount++;
      const randomSuffix = Math.random().toString(36).substring(2, 6).toUpperCase();
      const formattedCount = String(currentCount).padStart(4, '0');
      const passId = `ETSN-2026-${formattedCount}-${randomSuffix}`;

      const newPart: Participant = {
        ...item,
        id: 'part-' + Math.random().toString(36).substring(2, 9),
        passId,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
      };
      this.data.participants.push(newPart);
      created.push(newPart);
    }
    this.save();
    return created;
  }

  updateParticipant(id: string, updates: Partial<Omit<Participant, 'id' | 'passId' | 'createdAt'>>): Participant | undefined {
    const index = this.data.participants.findIndex(p => p.id === id);
    if (index === -1) return undefined;

    this.data.participants[index] = {
      ...this.data.participants[index],
      ...updates,
      updatedAt: new Date().toISOString()
    };
    this.save();
    return this.data.participants[index];
  }

  deleteParticipant(id: string): boolean {
    const index = this.data.participants.findIndex(p => p.id === id);
    if (index === -1) return false;
    this.data.participants.splice(index, 1);
    this.save();
    return true;
  }

  deleteParticipantsBatch(ids: string[]): boolean {
    const initialLength = this.data.participants.length;
    this.data.participants = this.data.participants.filter(p => !ids.includes(p.id));
    this.save();
    return this.data.participants.length < initialLength;
  }

  // --- Scan Logs Methods ---
  getScanLogs(): ScanLog[] {
    // Populate with participant names for display convenience
    return this.data.scanLogs.map(log => {
      const part = this.getParticipantByPassId(log.passId);
      return {
        ...log,
        participantName: part ? part.fullName : log.participantName || 'Unknown'
      };
    });
  }

  addScanLog(log: Omit<ScanLog, 'id' | 'createdAt'>): ScanLog {
    const newLog: ScanLog = {
      ...log,
      id: 'log-' + Math.random().toString(36).substring(2, 9),
      createdAt: new Date().toISOString()
    };
    this.data.scanLogs.push(newLog);
    this.save();
    return newLog;
  }

  clearScanLogs(): void {
    this.data.scanLogs = [];
    this.save();
  }
}

export const db = new DB();
